// Generated by gencpp from file get_pointcloud/Obsposelist.msg
// DO NOT EDIT!


#ifndef GET_POINTCLOUD_MESSAGE_OBSPOSELIST_H
#define GET_POINTCLOUD_MESSAGE_OBSPOSELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/TransformStamped.h>

namespace get_pointcloud
{
template <class ContainerAllocator>
struct Obsposelist_
{
  typedef Obsposelist_<ContainerAllocator> Type;

  Obsposelist_()
    : obs_poses_list()  {
    }
  Obsposelist_(const ContainerAllocator& _alloc)
    : obs_poses_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::TransformStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::TransformStamped_<ContainerAllocator> >> _obs_poses_list_type;
  _obs_poses_list_type obs_poses_list;





  typedef boost::shared_ptr< ::get_pointcloud::Obsposelist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::get_pointcloud::Obsposelist_<ContainerAllocator> const> ConstPtr;

}; // struct Obsposelist_

typedef ::get_pointcloud::Obsposelist_<std::allocator<void> > Obsposelist;

typedef boost::shared_ptr< ::get_pointcloud::Obsposelist > ObsposelistPtr;
typedef boost::shared_ptr< ::get_pointcloud::Obsposelist const> ObsposelistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::get_pointcloud::Obsposelist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::get_pointcloud::Obsposelist_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::get_pointcloud::Obsposelist_<ContainerAllocator1> & lhs, const ::get_pointcloud::Obsposelist_<ContainerAllocator2> & rhs)
{
  return lhs.obs_poses_list == rhs.obs_poses_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::get_pointcloud::Obsposelist_<ContainerAllocator1> & lhs, const ::get_pointcloud::Obsposelist_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace get_pointcloud

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::get_pointcloud::Obsposelist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::get_pointcloud::Obsposelist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::get_pointcloud::Obsposelist_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0aaa214c546cd6dd8dd28dc01d8ebbac";
  }

  static const char* value(const ::get_pointcloud::Obsposelist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0aaa214c546cd6ddULL;
  static const uint64_t static_value2 = 0x8dd28dc01d8ebbacULL;
};

template<class ContainerAllocator>
struct DataType< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "get_pointcloud/Obsposelist";
  }

  static const char* value(const ::get_pointcloud::Obsposelist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/TransformStamped[] obs_poses_list\n"
"================================================================================\n"
"MSG: geometry_msgs/TransformStamped\n"
"# This expresses a transform from coordinate frame header.frame_id\n"
"# to the coordinate frame child_frame_id\n"
"#\n"
"# This message is mostly used by the \n"
"# <a href=\"http://wiki.ros.org/tf\">tf</a> package. \n"
"# See its documentation for more information.\n"
"\n"
"Header header\n"
"string child_frame_id # the frame id of the child frame\n"
"Transform transform\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Transform\n"
"# This represents the transform between two coordinate frames in free space.\n"
"\n"
"Vector3 translation\n"
"Quaternion rotation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::get_pointcloud::Obsposelist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obs_poses_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Obsposelist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::get_pointcloud::Obsposelist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::get_pointcloud::Obsposelist_<ContainerAllocator>& v)
  {
    s << indent << "obs_poses_list[]" << std::endl;
    for (size_t i = 0; i < v.obs_poses_list.size(); ++i)
    {
      s << indent << "  obs_poses_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::TransformStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.obs_poses_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GET_POINTCLOUD_MESSAGE_OBSPOSELIST_H
