#footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]

#important
#TODO define footprint_model parameter of type circle and radius 40cm (Three lines)
#TODO check the instruction pdf for more info
footprint_model:
    type: "circular"
    radius: 0.40
# robot_radius: 0.25
# footprint_padding: 0.01


robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions

#following lines specify which topic to use to get obstacle positions
#TODO in topic field specify the topic in which you are getting the laserscan data
obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: pointcloud_scan, inf_is_valid: true}

#important
#TODO define inflation  parameter of  radius 25cm  and cost_scaling_factor of 4.0
#TODO check the instruction pdf for more info
#TODO Question what is the inflation parameter, what is the use for it,explain breifly the use of inflation radius and cost scaling factor ?
inflation:
    inflation_radius: 0.25
    cost_scaling_factor: 4.0